// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SkillUp.Infrastructure;

#nullable disable

namespace SkillUp.Infrastructure.Migrations
{
    [DbContext(typeof(SkillUpDbContext))]
    [Migration("20251113004433_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillUp.Domain.Entities.Curso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CargaHoraria")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CARGA_HORARIA");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DIFICULDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id")
                        .HasName("PK_SKILLUP_CURSO");

                    b.ToTable("SKILLUP_CURSO", (string)null);
                });

            modelBuilder.Entity("SkillUp.Domain.Entities.Progresso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROGRESSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CursoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CURSO");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_INICIO");

                    b.Property<decimal>("Porcentagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("PORCENTAGEM");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("NaoIniciado")
                        .HasColumnName("STATUS");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id")
                        .HasName("PK_SKILLUP_PROGRESSO");

                    b.HasIndex("CursoId");

                    b.HasIndex("UsuarioId", "CursoId")
                        .IsUnique()
                        .HasDatabaseName("UX_PROGRESSO_USUARIO_CURSO");

                    b.ToTable("SKILLUP_PROGRESSO", (string)null);
                });

            modelBuilder.Entity("SkillUp.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaInteresse")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("AREA_INTERESSE");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id")
                        .HasName("PK_SKILLUP_USUARIO");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_SKILLUP_USUARIO_EMAIL");

                    b.ToTable("SKILLUP_USUARIO", (string)null);
                });

            modelBuilder.Entity("SkillUp.Domain.Entities.Progresso", b =>
                {
                    b.HasOne("SkillUp.Domain.Entities.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROGRESSO_CURSO");

                    b.HasOne("SkillUp.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROGRESSO_USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
